version: "3.9"

services:
 mysqldb:
  image: mysql
  ports:
   - "13306:3306"
  volumes:
   - mysql:/var/lib/mysql
   - mysql_config:/etc/mysql
  networks:
   bank_service:
  environment:
   MYSQL_ROOT_PASSWORD: p#ssw0rd1
   MYSQL_DATABASE: bank_balance
 web:
  build:
   context: .
  ports:
  - "8000:8888"
  command: bash -c "python3 -m uvicorn main:app --host 0.0.0.0 --port 8888"
  volumes:
  - .:/code
  networks:
   bank_service:

volumes:
  mysql:
  mysql_config:

networks:
 bank_service:
