version: "3.9"

services:
 mysqldb:
  image: mysql
  ports:
   - "13306:3306"
  volumes:
   - mysql:/var/lib/mysql
   - mysql_config:/etc/mysql
  networks:
  - backend_net
  environment:
   MYSQL_ROOT_PASSWORD: p#ssw0rd1
   MYSQL_DATABASE: bank_balance

 rabbitmq:
  image: rabbitmq:3.9-management
  ports:
   - "5672:5672"
   - "15672:15672"
  volumes:
    - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
    - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    - ./rabbitmq/logs:/var/log/rabbitmq/log
  networks:
  - backend_net

 operations_worker:
  build:
   context: .
  command: bash -c "celery -A celery_app worker --loglevel=info -Q created_operations,pending_operations -n operations_worker"
  volumes:
   - .:/code
  environment:
   CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
  networks:
   - backend_net
  depends_on:
   - rabbitmq
   - mysqldb

 web:
  build:
   context: .
  ports:
  - "8000:8888"
  command: bash -c "python3 -m uvicorn main:app --host 0.0.0.0 --port 8888 --reload"
  volumes:
  - .:/code
  networks:
  - backend_net
  depends_on:
   - mysqldb

volumes:
  mysql:
  mysql_config:

networks:
 backend_net:
