"""operation amount float to decimal

Revision ID: 5be1d5fdfbe7
Revises: a7ce5644c827
Create Date: 2022-04-15 09:19:37.411924

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5be1d5fdfbe7'
down_revision = 'a7ce5644c827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation', 'amount',
                    existing_type=mysql.FLOAT(),
                    type_=sa.DECIMAL(precision=14, scale=4),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation', 'amount',
                    existing_type=sa.DECIMAL(precision=14, scale=4),
                    type_=mysql.FLOAT(),
                    existing_nullable=False)
    # ### end Alembic commands ###
