"""operation amount float to decimal

Revision ID: a7ce5644c827
Revises: d6a47fa8aeb2
Create Date: 2022-04-14 18:07:23.062287

"""

# revision identifiers, used by Alembic.
revision = 'a7ce5644c827'
down_revision = 'd6a47fa8aeb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
